### ISSUE TITLE
heroku crashes

### ISSUE THREAD

**Issue by ozdaldogru** [ozdaldogru/Gamersheim-Interactive-Full-Stack-Project-#92]

**Comment by justinsta624** [comment]
Hey Ozdal, hopefully everything goes well

It seems like you have a problem with HEROKU crashes.
Did you try "npm run seed" in HEROKU console? because I solved the HEROKU deploy error by doing this as following screenshot, while doing Challenge 14
* Open HEROKU app for this project -> Click "More" -> Click "Run console" -> Type "npm run seed"

![Screenshot 2024-02-06 203354](https://github.com/ozdaldogru/Gamersheim-Interactive-Full-Stack-Project-/assets/143357899/c2510e4f-b5dc-4c58-873d-d0632cd88c16)
![Screenshot 2024-02-06 203413](https://github.com/ozdaldogru/Gamersheim-Interactive-Full-Stack-Project-/assets/143357899/251adeb8-da02-49a3-a9b2-4f4611c26ef0)

**Comment by ozdaldogru** [comment]
Thank you so much Justin.
